version: "3"
services:
    api:
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
        restart: always
        container_name: api
        volumes:
        - ./.env:/opt/apt/.env
        networks: 
        - MyNetwork
    rmq:
        image: rabbitmq:3-management          
        restart: always
        networks: 
        - MyNetwork
        ports: 
        - 15672:15672
        - 5671:5671
        - 5672:5672
        environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin

networks:
    MyNetwork:
        driver: bridge
